### ISSUE TITLE
頁面存在橫向滾動條

### ISSUE THREAD

**Issue by JohnNiang** [hshanx/halo-theme-xue#1]
# 問題

頁面存在橫向滾動條。

# 可能原因

頭部包含背景圖片的 `div` 的 `class` 中設置了 `w-screen`。

**Comment by JohnNiang** [comment]
https://github.com/hshanx/halo-theme-xue/blob/1106b81ee0ab0ba4b77380263875fe58e8d166ce/index.ftl#L6

**Comment by hshanx** [comment]
Bug已修复
