### ISSUE TITLE
首页出现横向滚动条，页面显示问题

### ISSUE THREAD

**Issue by eelve** [hshanx/halo-theme-xue#10]
首页移动端显示问题，Flyme  8，默认浏览器
![S00726-20561511](https://user-images.githubusercontent.com/13844973/88479580-ba81fa80-cf82-11ea-8b85-a26af90b6289.png)

**Comment by hshanx** [comment]
你是用的哪个版本？

**Comment by eelve** [comment]
最新版本，我看的是你的博客。

**Comment by hshanx** [comment]
> 最新版本，我看的是你的博客。
那应该还是有内容超出了页面，可以帮忙看下超出了页面的是什么内容呢？

**Comment by eelve** [comment]
> > 最新版本，我看的是你的博客。
> > 那应该还是有内容超出了页面，可以帮忙看下超出了页面的是什么内容呢？

![S00728-10115214](https://user-images.githubusercontent.com/13844973/88611100-ebfde180-d0ba-11ea-929b-e6b11dccf181.png)
![S00728-10120031](https://user-images.githubusercontent.com/13844973/88611132-fa4bfd80-d0ba-11ea-9a6b-076c7d40d39f.png)

**Comment by hshanx** [comment]
> > > 最新版本，我看的是你的博客。
> > > 那应该还是有内容超出了页面，可以帮忙看下超出了页面的是什么内容呢？
> 


你的手机屏幕尺寸的多大的呢？多宽的呀？

**Comment by eelve** [comment]
> > > > 最新版本，我看的是你的博客。
> > > > 那应该还是有内容超出了页面，可以帮忙看下超出了页面的是什么内容呢？
> 
> 你的手机屏幕尺寸的多大的呢？多宽的呀？

![S00728-12261363](https://user-images.githubusercontent.com/13844973/88619338-ea89e480-d0cd-11ea-9000-94e6617daa60.png)

**Comment by hshanx** [comment]
确实有点问题，在1.1.2 版本修复了该问题@eelve

**Comment by eelve** [comment]
> 
> 
> 确实有点问题，在1.1.2 版本修复了该问题@eelve

看了最新版本，已经修复好了
