### ISSUE TITLE
友情链接能不能根据是否有logo是否有desc来使用不同的样式

### ISSUE THREAD

**Issue by sheiy** [hshanx/halo-theme-xue#13]
![image](https://user-images.githubusercontent.com/12210038/88545759-fc2ba780-d04d-11ea-9e5e-08b22417a288.png)

**Comment by sheiy** [comment]
如果没有logo没有desc那样式丑了点

**Comment by hshanx** [comment]
> 如果没有logo没有desc那样式丑了点

比如说什么样式呢？没有logo会有一个默认logo

**Comment by sheiy** [comment]
其实我想要这种效果，在没有描述和logo的情况下
![image](https://user-images.githubusercontent.com/12210038/88622062-828acc80-d0d4-11ea-9f11-403813d878a7.png)

**Comment by hshanx** [comment]
> 其实我想要这种效果，在没有描述和logo的情况下
> ![image](https://user-images.githubusercontent.com/12210038/88622062-828acc80-d0d4-11ea-9f11-403813d878a7.png)

这种会影响到目前友链card的结构了。所以不考虑这么弄了，如果你需要的话，可以自定义哟。
