### ISSUE TITLE
关于悬浮显示简介的建议

### ISSUE THREAD

**Issue by codesensi** [hshanx/halo-theme-xue#14]
个人希望的样式是鼠标放在图片上时，图片模糊化，简介显示在居中的位置。大佬如果有兴趣的话，可以试一下。

**Comment by hshanx** [comment]
开发的时候试了下这个，感觉不是怎么好，就改成现在的样子了

**Comment by codesensi** [comment]
搜嘎，我了解了

**Comment by hshanx** [comment]
> 搜嘎，我了解了

哈哈，其实悬浮显示也蛮好的😂
