### ISSUE TITLE
关于标签云显示方式和社交网络页面提示的建议

### ISSUE THREAD

**Issue by codesensi** [hshanx/halo-theme-xue#16]
1、标签云显示方式：一般来说，标签是比较多的，所以横向显示（一行显示若干个标签，而不是现在的一行显示一个标签）是不是更合适一点，并且title属性提示每个标签下的文章数量。
2、社交网络：title属性提示后台设置的值，比如QQ，提示的是QQ号。并且GitHub的href属性直接写成https://github.com/${setting}，${setting}是指后台设置的GitHub用户昵称。同样的，title属性提示的是用户昵称。
以上
这些都是个人建议，大佬觉得有必要的话可以采纳一下，大佬万安。

**Comment by hshanx** [comment]
标签云有范例吗？可以来一个看看

**Comment by codesensi** [comment]
这是Sakura主题的标签云样式
![Screenshot_20200730-121659](https://user-images.githubusercontent.com/66196408/88880882-7c295b80-d260-11ea-8f8c-260d20cd3329.jpg)
寒山主题的也是我说的一行显示若干标签的样式，这个钥匙莫得截图

**Comment by hshanx** [comment]
这个样式确实不错哈

**Comment by codesensi** [comment]
是挺好看的，但是我太菜了，并没有能力copy

**Comment by codesensi** [comment]
还有个小建议，把文章页文章标题下方的昵称换成文章分类，感觉会更舒服一点

**Comment by hshanx** [comment]
> 还有个小建议，把文章页文章标题下方的昵称换成文章分类，感觉会更舒服一点

这个之前有想做，但是也一直都没有搞。因为现在展示名字有点多余

**Comment by codesensi** [comment]
完美，感谢大佬

**Comment by HaoNanZhao** [comment]
请问楼上大佬一号和大佬二号  这个标签云怎么加到我的博客中啊  我更新了最新的1.1.4的主题 但没找到该功能  前端一点不会  希望指教一下

**Comment by HaoNanZhao** [comment]
> 完美，感谢大佬

请问楼上大佬一号和大佬二号 这个标签云怎么加到我的博客中啊 我更新了最新的1.1.4的主题 但没找到该功能 前端一点不会 希望指教一下

**Comment by hshanx** [comment]
> > 完美，感谢大佬
> 
> 请问楼上大佬一号和大佬二号 这个标签云怎么加到我的博客中啊 我更新了最新的1.1.4的主题 但没找到该功能 前端一点不会 希望指教一下

菜单加一个标签项就可以了

**Comment by HaoNanZhao** [comment]
> > > 完美，感谢大佬
> > 
> > 
> > 请问楼上大佬一号和大佬二号 这个标签云怎么加到我的博客中啊 我更新了最新的1.1.4的主题 但没找到该功能 前端一点不会 希望指教一下
> 
> 菜单加一个标签项就可以了

菜单
![Uploading image.png…]()
菜单中新建一个模块  那么地址咋填呀  跟友链  图库那些页面的添加不一样吧

**Comment by HaoNanZhao** [comment]
请问更新了主题以后  标签项的页面会在所有页面中出现么。我的没有找到，还有一个问题需要请教一下，楼主的首页是16个文章铺满对齐了  为啥我的只有十个，第十一个就在下一页了呢。多有打扰，谢谢了

**Comment by codesensi** [comment]
> 请问更新了主题以后 标签项的页面会在所有页面中出现么。我的没有找到，还有一个问题需要请教一下，楼主的首页是16个文章铺满对齐了 为啥我的只有十个，第十一个就在下一页了呢。多有打扰，谢谢了

菜单中添加，标签地址是/tags，分类是/categories，分页是在halo后台里设置的，仔细找一下

**Comment by HaoNanZhao** [comment]
> > 请问更新了主题以后 标签项的页面会在所有页面中出现么。我的没有找到，还有一个问题需要请教一下，楼主的首页是16个文章铺满对齐了 为啥我的只有十个，第十一个就在下一页了呢。多有打扰，谢谢了
> 
> 菜单中添加，标签地址是/tags，分类是/categories，分页是在halo后台里设置的，仔细找一下

感谢二位！！！整好了！！！
