### ISSUE TITLE
友链页面头像未自动适应

### ISSUE THREAD

**Issue by codesensi** [hshanx/halo-theme-xue#17]
友链页面头像未自动适应
![Uploading Screenshot_20200730-094931.jpg…](示例图)

**Comment by codesensi** [comment]
![Screenshot_20200730-094931](https://user-images.githubusercontent.com/66196408/88878424-89dbe280-d25a-11ea-9c79-b49d70599fb6.jpg)

**Comment by hshanx** [comment]
请参考最新版本

**Comment by codesensi** [comment]
完美，大佬辛苦
