### ISSUE TITLE
访问人数以及浏览量不显示

### ISSUE THREAD

**Issue by javami888** [hshanx/halo-theme-xue#18]
<#if settings.TimeStatistics??>
                    <div class="github-badge">
                        <a style="color: #fff" rel="license" href="javascript:void(0)"
                           target="_blank">
                            <span class="badge-subject">运行</span>
                            <span class="badge-value bg-orange" id="span_dt_dt"></span>
                        </a>
                    </div>
                </#if>
                <#if settings.visit_statistics!false>
                	<p>
                    	<span class="badge-subject" id="busuanzi_container_site_uv">感谢<span  id="busuanzi_value_site_uv"></span>位小伙伴的</span>
                    	<span id="busuanzi_container_site_pv"><span id="busuanzi_value_site_pv"></span>次访问</span>
                	</p>
               </#if>
运行时间是ok的  但是访问就是不出来

**Comment by hshanx** [comment]
因为都没有这个功能

**Comment by hshanx** [comment]
最新版本实现，请使用最新版本

**Comment by javami888** [comment]
我是使用的就是最新版本啊&nbsp; 雪么&nbsp; &nbsp;之前寒山 底部有统计浏览量但是雪没找到，我就把寒山的这部分代码复制过去了








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hshanx"<notifications@github.com&gt;; 
发送时间: 2020年7月31日(星期五) 晚上11:16
收件人: "hshanx/halo-theme-xue"<halo-theme-xue@noreply.github.com&gt;; 
抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [hshanx/halo-theme-xue] 访问人数以及浏览量不显示 (#18)





 
最新版本实现，请使用最新版本

**Comment by javami888** [comment]
好的谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hshanx"<notifications@github.com&gt;; 
发送时间: 2020年7月31日(星期五) 晚上10:57
收件人: "hshanx/halo-theme-xue"<halo-theme-xue@noreply.github.com&gt;; 
抄送: "黑晶石"<miguannan@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [hshanx/halo-theme-xue] 访问人数以及浏览量不显示 (#18)





 
因为都没有这个功能
