### ISSUE TITLE
Markdown主题问题

### ISSUE THREAD

**Issue by James-Hao** [hshanx/halo-theme-xue#19]
大佬好~从寒山主题跟随到这哈哈，请教大佬，我在雪主题中将用typora的vue主题编写的markdown文件上传后，在主题中文章显示造成一些高亮部分不显示，还有代码的颜色变得浅的问题，问仙哥说应该是主题问题，想请教大佬可以怎样改进，感谢！

**Comment by hshanx** [comment]
来个链接呢

**Comment by James-Hao** [comment]
> 来个链接呢

大佬我发您一个mk文件吧~ 你导入后台一下看看哈哈 我放链接感觉不明显，辛苦大佬！😝 （怎么上传文件呀哈哈）

**Comment by hshanx** [comment]
> > 来个链接呢
> 
> 大佬我发您一个mk文件吧~ 你导入后台一下看看哈哈 我放链接感觉不明显，辛苦大佬！😝 （怎么上传文件呀哈哈）

![image](https://user-images.githubusercontent.com/23736683/88942161-75303680-d2bc-11ea-82fe-bdc92b81acc7.png)

**Comment by James-Hao** [comment]
> > > 来个链接呢
> > 
> > 
> > 大佬我发您一个mk文件吧~ 你导入后台一下看看哈哈 我放链接感觉不明显，辛苦大佬！😝 （怎么上传文件呀哈哈）
> 
> ![image](https://user-images.githubusercontent.com/23736683/88942161-75303680-d2bc-11ea-82fe-bdc92b81acc7.png)


好嘞~ 传给您一份

**Comment by James-Hao** [comment]
> > > 来个链接呢
> > 
> > 
> > 大佬我发您一个mk文件吧~ 你导入后台一下看看哈哈 我放链接感觉不明显，辛苦大佬！😝 （怎么上传文件呀哈哈）
> 
> ![image](https://user-images.githubusercontent.com/23736683/88942161-75303680-d2bc-11ea-82fe-bdc92b81acc7.png)

sorry,刚才手滑点错了
[md文件.zip](https://github.com/hshanx/halo-theme-xue/files/5002285/md.zip)
文件发给您啦，辛苦大佬~🤣

**Comment by James-Hao** [comment]
> 请看1.1.4版本，选择不同的代码风格
> ![image](https://user-images.githubusercontent.com/23736683/88952998-db23ba80-d2ca-11ea-8e81-ed732be4d513.png)

nice~~更新了一下 有typora的vue主题吗请问大佬~🤣

**Comment by hshanx** [comment]
> > 请看1.1.4版本，选择不同的代码风格
> > ![image](https://user-images.githubusercontent.com/23736683/88952998-db23ba80-d2ca-11ea-8e81-ed732be4d513.png)
> 
> nice~~更新了一下 有typora的vue主题吗请问大佬~🤣

小伙子，没有的
