### ISSUE TITLE
自定义模板友链页不显示头部图

### ISSUE THREAD

**Issue by codesensi** [hshanx/halo-theme-xue#20]
如题：自定义模板友链页不显示头部图，PC端和手机端都不显示
站点：https://codesensi.top/

**Comment by codesensi** [comment]
![Screenshot_20200731-142503](https://user-images.githubusercontent.com/66196408/89006860-32ad3f00-d33a-11ea-8f4c-d6e202caa3e9.jpg)
大佬，标签没有左对齐，看着有点难受😭，这个怎么修改，方便的话告诉我一下是哪个css控制的

**Comment by hshanx** [comment]
最新版本实现，请使用最新版本

**Comment by codesensi** [comment]
> 最新版本实现，请使用最新版本

大佬万安
