### ISSUE TITLE
随机图问题

### ISSUE THREAD

**Issue by codesensi** [hshanx/halo-theme-xue#22]
1：首页第一篇文章不会自动使用随机图
![image](https://user-images.githubusercontent.com/66196408/89052862-e89f7a00-d388-11ea-96ad-431c722118ab.png)

2：文章页头部不显示相应的随机图
![image](https://user-images.githubusercontent.com/66196408/89052927-010f9480-d389-11ea-9bcf-51c6a984ea11.png)

PS：哈哈哈哈哈，大佬，我一天老提问题，你是不是很绝望

**Comment by codesensi** [comment]
大佬，第一篇文章不显示随机图是我弄错了，少了个thumbnail-0，打扰了

**Comment by hshanx** [comment]
我觉得文章页其实不怎么需要随机图，并且这里实现起来也不是怎么灵活

**Comment by codesensi** [comment]
搜噶，那这样就完全OK了，顺便提一下，logo图那里也没有自适应😜
