### ISSUE TITLE
归档文章中，只能首页和归档菜单有效，其他菜单失效

### ISSUE THREAD

**Issue by eelve** [hshanx/halo-theme-xue#24]
操作步骤：

- 1.点击归档
- 2.点击一篇文章，查看
- 3.点击图库菜单等出现不能跳转问题

![图片](https://user-images.githubusercontent.com/13844973/89143476-4ac0d080-d57d-11ea-8006-71293d0b0c21.png)

以上图片为报错信息，推测为其他菜单连接在归档文章中多拼接了`archives`，比如：https://eelve.com/archives/photos

**Comment by hshanx** [comment]
这是你写错了吧，你后台创建目录的时候，是不是少写了 一个斜杠 `/`
![image](https://user-images.githubusercontent.com/23736683/89145130-582c8980-d582-11ea-903f-3048062f23c2.png)

**Comment by eelve** [comment]
> 
> 
> 这是你写错了吧，你后台创建目录的时候，是不是少写了 一个斜杠 `/`
> ![image](https://user-images.githubusercontent.com/23736683/89145130-582c8980-d582-11ea-903f-3048062f23c2.png)

按照提示已经修改了
