### ISSUE TITLE
博客内容界面右侧的目录无法自动更新

### ISSUE THREAD

**Issue by rabbidss** [hshanx/halo-theme-xue#3]
博客内容界面右侧的目录无法自动更新

**Comment by hshanx** [comment]
无法自动更新是什么意思呀？

**Comment by rabbidss** [comment]
![image](https://user-images.githubusercontent.com/56468889/87769739-9e7aac80-c850-11ea-96af-3d789a4ccc55.png)
按道理当我移动到第二个标题下这个目录用个会动态的展示吧，现在只有我刷新页面这个目录才会更新
![image](https://user-images.githubusercontent.com/56468889/87769935-e8fc2900-c850-11ea-9507-4a61db9818b5.png)

**Comment by rabbidss** [comment]
我不晓得这是不是我服务器的原因还是怎么了。。。

**Comment by hshanx** [comment]
感觉是js报错了，你把你网站发我看下呢

**Comment by rabbidss** [comment]
http://blog.jingxindeyi.cn/archives/flink

网页在这
