### ISSUE TITLE
v1.0.1依旧存在横向滚动条，且存在文本超出文本框情况

### ISSUE THREAD

**Issue by rabbidss** [hshanx/halo-theme-xue#4]
![image](https://user-images.githubusercontent.com/56468889/87773118-46927480-c855-11ea-8a72-df34c74ecb17.png)

**Comment by hshanx** [comment]
额，来个截图呢

**Comment by rabbidss** [comment]
你好，我看了一下这个超出文本应该是是markdown不支持scala语言的问题

**Comment by rabbidss** [comment]
大佬这个有对移动端做适配吗，做了的话也有些小问题

**Comment by hshanx** [comment]
> 大佬这个有对移动端做适配吗，做了的话也有些小问题

什么问题呢？来个具体描述

**Comment by rabbidss** [comment]
> > 大佬这个有对移动端做适配吗，做了的话也有些小问题
> 
> 什么问题呢？来个具体描述



> > 大佬这个有对移动端做适应吗，做成的话也有些小问题
> 
> 什么问题呢？来个具体描述

主要是换行的问题，网页链接太长的话不会换行，然后就又把底部滚动条撑出来了

**Comment by rabbidss** [comment]
> > > 大佬这个有对移动端做适应吗，做成的话也有些小问题
> > 
> > 
> > 什么问题呢？来个具体描述
> 
> > > 大佬这个有对移动端做适应吗，造成的话也有些小问题
> > 
> > 
> > 什么问题呢？来个具体描述
> 
> 主要是换行的问题，网页链接太长的话不会换行，然后就又把底部滚动条撑出来了

http://blog.jingxindeyi.cn/archives/liux  可以用手机看一下这个

**Comment by hshanx** [comment]
> > > > 大佬这个有对移动端做适应吗，做成的话也有些小问题
> > > 
> > > 
> > > 什么问题呢？来个具体描述
> > 
> > 
> > > > 大佬这个有对移动端做适应吗，造成的话也有些小问题
> > > 
> > > 
> > > 什么问题呢？来个具体描述
> > 
> > 
> > 主要是换行的问题，网页链接太长的话不会换行，然后就又把底部滚动条撑出来了
> 
> http://blog.jingxindeyi.cn/archives/liux 可以用手机看一下这个

![image](https://user-images.githubusercontent.com/23736683/87877340-5b673780-ca10-11ea-837e-75d03baa8f10.png)

这个吗？

**Comment by rabbidss** [comment]
是的，电脑上调试看不出来 但是用手机进就有横向滚动条了
大佬顺便看一下那个目录不更新的问题

**Comment by hshanx** [comment]
> 是的，电脑上调试看不出来 但是用手机进就有横向滚动条了
> 大佬顺便看一下那个目录不更新的问题
你把你的网站发我看看

**Comment by hshanx** [comment]
这个issue在最新的发布版本已经修复了，你可以下载试下

**Comment by hshanx** [comment]
> 是的，电脑上调试看不出来 但是用手机进就有横向滚动条了
> 大佬顺便看一下那个目录不更新的问题

问题都已修复，请下载最新版本

**Comment by rabbidss** [comment]
> > 是的，电脑上调试看不出来 但是用手机进就有横向滚动条了
> > 大佬顺便看一下那个目录不更新的问题
> 
> 问题都已修复，请下载最新版本

好的，大佬牛批666
