### ISSUE TITLE
希望能支持数学公式，比如MathJax

### ISSUE THREAD

**Issue by GuiZi** [hshanx/halo-theme-xue#5]
希望能支持数学公式，比如MathJax
我用的halo是1.3.1版本，虽然开启了Mathjax，但是很不理想，可以说不支持
谢谢

**Comment by hshanx** [comment]
你是怎么写的呢？我本地试了下是可以的，你发一个数学公式给我试试

**Comment by GuiZi** [comment]
> 你是怎么写的呢？我本地试了下是可以的，你发一个数学公式给我试试

这是MathJax的官方例子，有行内公式，也有块公式：
When $a \ne 0$, there are two solutions to \(ax^2 + bx + c = 0\) and they are
$$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$

**Comment by hshanx** [comment]
这个问题已经部分解决。目前在halo返回的Markdown文本有问题，无法正常显示，请关注下面的issue
https://github.com/halo-dev/halo/issues/982

**Comment by GuiZi** [comment]
谢谢解答
